### Actor
### getActorByID
POST http://localhost:9090/SakilaApi/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://actorServices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:actor>
            <arg0>3</arg0>
        </jets:actor>
    </soap:Body>
</soap:Envelope>

### getAllActors
POST http://localhost:9090/SakilaApi/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://actorServices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:actors>
        </jets:actors>
    </soap:Body>
</soap:Envelope>
### addActor
POST http://localhost:9090/SakilaApi/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://actorServices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:addActor>
            <arg0>
             <firstName>Shaimaa</firstName>
        <lastName>CHASE</lastName>
        <lastUpdate>2006-02-15T04:34:33+02:00</lastUpdate>
            </arg0>
        </jets:addActor>
    </soap:Body>
</soap:Envelope>

### updateActor
POST http://localhost:9090/SakilaApi/ws/actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://actorServices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:updateActor>
            <arg0>
           <firstName>Shaimaa</firstName>
        <id>3</id>
        <lastName>Hassan</lastName>
        <lastUpdate>2006-02-15T04:34:33+02:00</lastUpdate>
            </arg0>
        </jets:updateActor>
    </soap:Body>
</soap:Envelope>