### Inventory
### Get Inventory
POST http://localhost:9090/SakilaApi/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://inventoryservices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:inventory>
            <arg0>411</arg0>
        </jets:inventory>
    </soap:Body>
</soap:Envelope>
### Get Film
POST http://localhost:9090/SakilaApi/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://inventoryservices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:film>
            <arg0>3</arg0>
        </jets:film>
    </soap:Body>
</soap:Envelope>
### Get Inventories
POST http://localhost:9090/SakilaApi/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://inventoryservices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:inventories>
        </jets:inventories>
    </soap:Body>
</soap:Envelope>
### Get Store
POST http://localhost:9090/SakilaApi/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

     xmlns:jets="http://inventoryservices.soapApi.api.myapi.com/">

    <soap:Body>
        <jets:store>
           <arg0>3</arg0>
        </jets:store>
    </soap:Body>
</soap:Envelope>